-- =============================================
-- Drop and Recreate career_questions Table
-- Comprehensive question set: 120+ questions
-- All streams, qualifications, interests covered (10+ each)
-- =============================================

USE career_guide_db;

DROP TABLE IF EXISTS career_questions;

CREATE TABLE IF NOT EXISTS career_questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    qualification VARCHAR(100) DEFAULT NULL,
    interest VARCHAR(100) DEFAULT NULL,
    age_min INT DEFAULT NULL,
    age_max INT DEFAULT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option CHAR(1) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_category (category),
    INDEX idx_qualification (qualification),
    INDEX idx_interest (interest)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO career_questions (category, qualification, interest, age_min, age_max, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
('science', '12th', 'science', 15, 25, 'What is the powerhouse of the cell?', 'Nucleus', 'Mitochondria', 'Ribosome', 'Golgi apparatus', 'b'),
('science', '12th', 'science', 15, 25, 'Which gas is most abundant in the Earth\'s atmosphere?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon', 'c'),
('science', '12th', 'science', 15, 25, 'What is the chemical symbol for water?', 'H2O', 'CO2', 'NaCl', 'O2', 'a'),
('science', '12th', 'science', 15, 25, 'Which planet is known as the Red Planet?', 'Venus', 'Jupiter', 'Mars', 'Saturn', 'c'),
('science', '12th', 'education', 15, 25, 'What is the speed of light in vacuum?', '3 x 10^6 m/s', '3 x 10^8 m/s', '3 x 10^10 m/s', '3 x 10^5 m/s', 'b'),
('science', 'bachelor', 'science', 20, 35, 'Which law states that energy can neither be created nor destroyed?', 'Newton\'s First Law', 'Law of Conservation of Energy', 'Ohm\'s Law', 'Boyle\'s Law', 'b'),
('science', 'bachelor', 'science', 20, 35, 'What is the SI unit of electric current?', 'Volt', 'Watt', 'Ampere', 'Ohm', 'c'),
('science', 'master', 'science', 22, 40, 'Which particle has a positive charge?', 'Electron', 'Neutron', 'Proton', 'Photon', 'c'),
('science', '10th', 'science', 14, 20, 'What is the formula of common salt?', 'NaCl', 'KCl', 'CaCl2', 'MgCl2', 'a'),
('science', '10th', 'science', 14, 20, 'Which vitamin is produced by sunlight?', 'Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D', 'd'),
('commerce', '12th', 'business', 15, 25, 'What is the primary objective of financial accounting?', 'To minimize taxes', 'To provide information for decision making', 'To maximize sales', 'To track employee attendance', 'b'),
('commerce', '12th', 'business', 15, 25, 'Which of the following is an asset?', 'Accounts Payable', 'Loan', 'Cash', 'Capital', 'c'),
('commerce', '12th', 'business', 15, 25, 'What does GDP stand for?', 'Gross Domestic Product', 'General Domestic Price', 'Gross Daily Production', 'General Development Plan', 'a'),
('commerce', '12th', 'business', 15, 25, 'What is the full form of GST?', 'General Sales Tax', 'Goods and Services Tax', 'Government Service Tax', 'Gross Sales Total', 'b'),
('commerce', '12th', 'business', 15, 25, 'Which document records daily business transactions?', 'Ledger', 'Journal', 'Trial Balance', 'Balance Sheet', 'b'),
('commerce', 'bachelor', 'business', 20, 35, 'What is equity in accounting?', 'Total liabilities', 'Owner\'s residual interest in assets', 'Total revenue', 'Net profit', 'b'),
('commerce', 'bachelor', 'business', 20, 35, 'Which ratio measures ability to pay short-term debts?', 'Debt-to-equity ratio', 'Current ratio', 'Profit margin', 'Return on investment', 'b'),
('commerce', 'master', 'business', 22, 40, 'What is inflation?', 'Decrease in prices', 'Increase in employment', 'General increase in prices over time', 'Decrease in money supply', 'c'),
('commerce', '10th', 'business', 14, 20, 'What is the basic unit of currency in India?', 'Dollar', 'Rupee', 'Pound', 'Euro', 'b'),
('commerce', '10th', 'business', 14, 20, 'Who is known as the Father of Economics?', 'Karl Marx', 'Adam Smith', 'John Keynes', 'David Ricardo', 'b'),
('arts', '12th', 'creative', 15, 25, 'Who painted the Mona Lisa?', 'Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Michelangelo', 'c'),
('arts', '12th', 'creative', 15, 25, 'Which is the study of human societies and cultures?', 'Psychology', 'Anthropology', 'Biology', 'Geology', 'b'),
('arts', '12th', 'creative', 15, 25, 'Who wrote Romeo and Juliet?', 'Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Jane Austen', 'b'),
('arts', '12th', 'media', 15, 25, 'What is the study of past events called?', 'Geography', 'Political Science', 'History', 'Sociology', 'c'),
('arts', '12th', 'creative', 15, 25, 'Which language is considered the oldest in the world?', 'Latin', 'Greek', 'Sanskrit', 'Hebrew', 'c'),
('arts', 'bachelor', 'creative', 20, 35, 'What is the study of mind and behavior called?', 'Sociology', 'Psychology', 'Philosophy', 'Anthropology', 'b'),
('arts', 'bachelor', 'media', 20, 35, 'Who is the author of the book "The Republic"?', 'Aristotle', 'Socrates', 'Plato', 'Homer', 'c'),
('arts', 'master', 'creative', 22, 40, 'Which art movement is Salvador Dali associated with?', 'Impressionism', 'Cubism', 'Surrealism', 'Realism', 'c'),
('arts', '10th', 'creative', 14, 20, 'What is the national language of India?', 'English', 'Hindi', 'Sanskrit', 'Tamil', 'b'),
('arts', '10th', 'creative', 14, 20, 'Which Indian festival is the Festival of Lights?', 'Holi', 'Diwali', 'Eid', 'Christmas', 'b'),
('engineering', 'bachelor', 'technology', 20, 35, 'Which component stores charge in a circuit?', 'Resistor', 'Inductor', 'Capacitor', 'Diode', 'c'),
('engineering', 'bachelor', 'technology', 20, 35, 'What does CPU stand for?', 'Central Process Unit', 'Central Processing Unit', 'Computer Personal Unit', 'Central Processor Utility', 'b'),
('engineering', 'bachelor', 'technology', 20, 35, 'What is the unit of electrical resistance?', 'Ampere', 'Volt', 'Ohm', 'Watt', 'c'),
('engineering', 'bachelor', 'technology', 20, 35, 'Which material is the best conductor of electricity?', 'Wood', 'Rubber', 'Silver', 'Glass', 'c'),
('engineering', 'diploma', 'technology', 18, 30, 'What does RAM stand for?', 'Read Access Memory', 'Random Access Memory', 'Run Application Memory', 'Rapid Active Memory', 'b'),
('engineering', '12th', 'technology', 16, 25, 'What is the SI unit of force?', 'Joule', 'Pascal', 'Newton', 'Watt', 'c'),
('engineering', '12th', 'technology', 16, 25, 'What is the boiling point of water in Celsius?', '90 C', '100 C', '110 C', '120 C', 'b'),
('engineering', 'diploma', 'technology', 18, 30, 'Which gas is used in welding?', 'Nitrogen', 'Oxygen', 'Acetylene', 'Helium', 'c'),
('engineering', '12th', 'technology', 16, 25, 'What does CAD stand for?', 'Computer Aided Design', 'Computer Active Drawing', 'Central Auto Design', 'Creative Aided Drafting', 'a'),
('engineering', 'master', 'technology', 22, 40, 'What type of bridge is strongest for heavy loads?', 'Beam bridge', 'Arch bridge', 'Suspension bridge', 'Truss bridge', 'd'),
('medical', 'bachelor', 'healthcare', 20, 35, 'Which organ pumps blood in the body?', 'Lungs', 'Brain', 'Heart', 'Liver', 'c'),
('medical', 'bachelor', 'healthcare', 20, 35, 'What is the largest organ in the human body?', 'Liver', 'Brain', 'Skin', 'Heart', 'c'),
('medical', 'bachelor', 'healthcare', 20, 35, 'How many bones are in the adult human body?', '196', '206', '216', '226', 'b'),
('medical', 'bachelor', 'healthcare', 20, 35, 'Which blood group is the universal donor?', 'A+', 'B+', 'AB+', 'O-', 'd'),
('medical', 'master', 'healthcare', 22, 40, 'What is the normal body temperature in Celsius?', '35 C', '36.1 C', '37 C', '38 C', 'c'),
('medical', '12th', 'healthcare', 16, 25, 'Which vitamin deficiency causes scurvy?', 'Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D', 'c'),
('medical', '12th', 'healthcare', 16, 25, 'What is the function of white blood cells?', 'Carry oxygen', 'Fight infections', 'Clot blood', 'Transport nutrients', 'b'),
('medical', '12th', 'healthcare', 16, 25, 'Which organ produces insulin?', 'Liver', 'Kidney', 'Pancreas', 'Stomach', 'c'),
('medical', 'diploma', 'healthcare', 18, 30, 'What is the smallest bone in the human body?', 'Femur', 'Stapes', 'Radius', 'Patella', 'b'),
('medical', 'diploma', 'healthcare', 18, 30, 'Which part of brain controls balance?', 'Cerebrum', 'Cerebellum', 'Medulla', 'Thalamus', 'b'),
('computer-science', '12th', 'technology', 15, 30, 'What does HTML stand for?', 'Hyper Text Markup Language', 'High Tech Modern Language', 'Hyper Transfer Mark Language', 'Home Tool Markup Language', 'a'),
('computer-science', '12th', 'technology', 15, 30, 'Which language is primarily used for web styling?', 'Java', 'Python', 'CSS', 'C++', 'c'),
('computer-science', '12th', 'technology', 15, 30, 'What does URL stand for?', 'Uniform Resource Locator', 'Universal Reference Link', 'Unified Resource Language', 'Universal Resource Locator', 'a'),
('computer-science', 'bachelor', 'technology', 20, 35, 'Which data structure uses FIFO principle?', 'Stack', 'Queue', 'Array', 'Tree', 'b'),
('computer-science', 'bachelor', 'technology', 20, 35, 'What is the binary of number 10?', '1000', '1010', '1100', '1001', 'b'),
('computer-science', 'bachelor', 'technology', 20, 35, 'Which sorting algorithm has the best average time?', 'Bubble Sort', 'Selection Sort', 'Merge Sort', 'Insertion Sort', 'c'),
('computer-science', 'master', 'technology', 22, 40, 'What does SQL stand for?', 'Structured Query Language', 'Simple Question Language', 'Standard Query Logic', 'System Query Language', 'a'),
('computer-science', 'master', 'technology', 22, 40, 'Which protocol is used for secure web communication?', 'HTTP', 'FTP', 'HTTPS', 'SMTP', 'c'),
('computer-science', 'diploma', 'technology', 18, 30, 'What is an API?', 'Advanced Programming Interface', 'Application Programming Interface', 'Automated Process Integration', 'Application Process Interaction', 'b'),
('computer-science', 'diploma', 'technology', 18, 30, 'Which is a NoSQL database?', 'MySQL', 'PostgreSQL', 'MongoDB', 'Oracle', 'c'),
('business', '12th', 'business', 16, 25, 'What is a startup?', 'A government organization', 'A newly established business', 'A stock market index', 'A type of loan', 'b'),
('business', '12th', 'business', 16, 25, 'What does CEO stand for?', 'Chief Executive Officer', 'Chief Education Officer', 'Central Executive Operation', 'Chief Engineering Officer', 'a'),
('business', 'bachelor', 'business', 20, 35, 'What is market segmentation?', 'Dividing market into groups', 'Selling products online', 'Reducing product price', 'Merging two companies', 'a'),
('business', 'bachelor', 'business', 20, 35, 'What is the 4P model in marketing?', 'Price Place Product Promotion', 'Plan Produce Price Profit', 'People Process Product Price', 'Product Profit Plan Place', 'a'),
('business', 'bachelor', 'business', 20, 35, 'What is a SWOT analysis?', 'Financial audit method', 'Strengths Weaknesses Opportunities Threats', 'Employee review process', 'Sales tracking system', 'b'),
('business', 'master', 'business', 22, 40, 'What is supply chain management?', 'Managing employee salaries', 'Managing flow of goods and services', 'Managing IT infrastructure', 'Managing marketing campaigns', 'b'),
('business', 'master', 'business', 22, 40, 'What is ROI?', 'Rate of Income', 'Return on Investment', 'Revenue of Industry', 'Ratio of Interest', 'b'),
('business', 'diploma', 'business', 18, 30, 'What is an entrepreneur?', 'A government employee', 'A person who starts a business', 'A banking official', 'A stock broker', 'b'),
('business', 'diploma', 'business', 18, 30, 'What is e-commerce?', 'Electronic education', 'Buying and selling online', 'Email communication', 'Electronic currency', 'b'),
('business', '10th', 'business', 14, 20, 'What is profit?', 'Total revenue', 'Revenue minus expenses', 'Total expenses', 'Revenue plus expenses', 'b'),
('arts', '12th', 'education', 15, 25, 'Who is known as the Father of Modern Education?', 'John Dewey', 'Aristotle', 'Plato', 'Confucius', 'a'),
('arts', 'bachelor', 'education', 20, 35, 'What is pedagogy?', 'Study of animals', 'Art of teaching', 'Study of plants', 'Study of rocks', 'b'),
('science', 'bachelor', 'education', 20, 35, 'What does STEM education stand for?', 'Science Teaching for Every Mind', 'Science Technology Engineering Math', 'Student Teacher Education Model', 'Standard Teaching Education Method', 'b'),
('science', 'master', 'education', 22, 40, 'What is Bloom\'s Taxonomy used for?', 'Classifying plants', 'Classifying learning objectives', 'Classifying diseases', 'Classifying rocks', 'b'),
('arts', 'master', 'education', 22, 40, 'What is the Montessori method?', 'Military training', 'Child-centered education approach', 'Online learning platform', 'Examination system', 'b'),
('science', '12th', 'education', 15, 25, 'What is the Right to Education Act in India?', 'Free education for ages 6-14', 'College scholarship program', 'Teacher training program', 'School building scheme', 'a'),
('arts', 'diploma', 'education', 18, 30, 'Which organization manages education policy in India?', 'RBI', 'NCERT', 'ISRO', 'DRDO', 'b'),
('commerce', 'bachelor', 'education', 20, 35, 'What is distance learning?', 'Learning by travel', 'Learning without physical classroom', 'Learning outdoors', 'Learning by experiments', 'b'),
('arts', '10th', 'education', 14, 20, 'What does a teacher primarily do?', 'Build houses', 'Teach students', 'Drive vehicles', 'Cook food', 'b'),
('science', 'diploma', 'education', 18, 30, 'What is a curriculum?', 'A type of exam', 'Planned course of study', 'A school building', 'A teaching award', 'b'),
('arts', '12th', 'social-services', 15, 25, 'What is social work?', 'Working in a factory', 'Helping people improve their lives', 'Working in IT', 'Working in a bank', 'b'),
('arts', 'bachelor', 'social-services', 20, 35, 'What is an NGO?', 'National Government Office', 'Non-Governmental Organization', 'New Global Operation', 'National Growth Organization', 'b'),
('arts', 'bachelor', 'social-services', 20, 35, 'What is community development?', 'Building apartments', 'Process of improving community well-being', 'Selling products', 'Government elections', 'b'),
('arts', 'master', 'social-services', 22, 40, 'Who founded the Red Cross?', 'Mahatma Gandhi', 'Henry Dunant', 'Nelson Mandela', 'Mother Teresa', 'b'),
('medical', 'bachelor', 'social-services', 20, 35, 'What is public health?', 'Private hospital management', 'Protecting health of populations', 'Selling medicines', 'Personal fitness', 'b'),
('commerce', '12th', 'social-services', 15, 25, 'What is a charitable trust?', 'A profit-making company', 'An organization for social benefit', 'A government department', 'A bank', 'b'),
('arts', 'diploma', 'social-services', 18, 30, 'What is counseling?', 'Selling products', 'Providing guidance and support', 'Teaching mathematics', 'Building roads', 'b'),
('arts', '10th', 'social-services', 14, 20, 'What does volunteer mean?', 'Paid worker', 'Person who works without pay to help others', 'Government employee', 'Company owner', 'b'),
('science', 'bachelor', 'social-services', 20, 35, 'What is environmental conservation?', 'Building factories', 'Protecting natural environment', 'Mining resources', 'Urban development', 'b'),
('arts', '12th', 'social-services', 16, 25, 'What is human rights?', 'Rights to own property only', 'Basic rights belonging to every person', 'Rights for government officials', 'Rights for rich people', 'b'),
('arts', '10th', 'sports', 14, 20, 'How many players are in a cricket team?', '9', '10', '11', '12', 'c'),
('arts', '12th', 'sports', 15, 25, 'What is the duration of a football match?', '60 minutes', '80 minutes', '90 minutes', '120 minutes', 'c'),
('science', '12th', 'sports', 15, 25, 'What is sports physiology?', 'Study of game rules', 'Study of body functions during exercise', 'Study of sports history', 'Study of team management', 'b'),
('medical', 'bachelor', 'sports', 20, 35, 'What is sports medicine?', 'Medicine for animals', 'Medical field for athletic injuries', 'General surgery', 'Dental care', 'b'),
('science', 'bachelor', 'sports', 20, 35, 'What is BMI?', 'Body Mass Index', 'Basic Medical Information', 'Body Muscle Indicator', 'Biological Mass Input', 'a'),
('arts', 'diploma', 'sports', 18, 30, 'What is a sports coach responsible for?', 'Cooking food', 'Training and guiding athletes', 'Building stadiums', 'Selling tickets', 'b'),
('medical', '12th', 'sports', 16, 25, 'What is a ligament?', 'A type of muscle', 'Tissue connecting bones', 'A blood vessel', 'A nerve ending', 'b'),
('science', 'master', 'sports', 22, 40, 'What is exercise kinesiology?', 'Study of nutrition', 'Study of body movement', 'Study of mental health', 'Study of diseases', 'b'),
('arts', 'bachelor', 'sports', 20, 35, 'What is sports management?', 'Playing sports', 'Business side of sports and recreation', 'Refereeing games', 'Building courts', 'b'),
('commerce', '12th', 'sports', 15, 25, 'What does sports marketing involve?', 'Playing games', 'Promoting sports events and products', 'Coaching athletes', 'Building stadiums', 'b'),
('arts', '12th', 'media', 15, 25, 'What is journalism?', 'Cooking', 'Gathering and reporting news', 'Painting', 'Building', 'b'),
('arts', 'bachelor', 'media', 20, 35, 'What is mass communication?', 'Talking to one person', 'Communicating to large audiences', 'Writing personal letters', 'Making phone calls', 'b'),
('arts', 'bachelor', 'media', 20, 35, 'What is a press release?', 'A gym exercise', 'Official statement to media', 'A type of printing', 'A court order', 'b'),
('computer-science', '12th', 'media', 15, 30, 'What is digital media?', 'Newspapers only', 'Content delivered via electronic devices', 'Radio only', 'Television only', 'b'),
('arts', 'master', 'media', 22, 40, 'What is media ethics?', 'Technical skills', 'Moral principles guiding media practice', 'Media equipment', 'Advertising strategy', 'b'),
('arts', 'diploma', 'media', 18, 30, 'What does a video editor do?', 'Write scripts', 'Arrange and modify video footage', 'Act in movies', 'Direct films', 'b'),
('business', '12th', 'media', 16, 25, 'What is social media marketing?', 'Meeting people in person', 'Promoting products through social platforms', 'Sending postal mail', 'Cold calling customers', 'b'),
('arts', '10th', 'media', 14, 20, 'What is a blog?', 'A type of food', 'An online journal or website', 'A musical instrument', 'A sport', 'b'),
('computer-science', 'bachelor', 'media', 20, 35, 'What is content management system?', 'Accounting software', 'Software for creating digital content', 'Email client', 'Database software', 'b'),
('arts', '12th', 'media', 15, 25, 'What is public relations?', 'Personal relationships', 'Managing public image of organizations', 'Government policy', 'Private investigation', 'b'),
('science', 'phd', 'science', 25, 50, 'What is a research hypothesis?', 'A proven fact', 'A testable prediction', 'A final conclusion', 'A data table', 'b'),
('science', 'phd', 'science', 25, 50, 'What is peer review in research?', 'Student grading', 'Evaluation by experts in same field', 'Public voting', 'Self-assessment', 'b'),
('medical', 'phd', 'healthcare', 25, 50, 'What is clinical research?', 'Teaching in classrooms', 'Research involving human participants', 'Library study', 'Computer programming', 'b'),
('computer-science', 'phd', 'technology', 25, 50, 'What is machine learning?', 'Mechanical repair', 'AI systems that learn from data', 'Manual data entry', 'Hardware installation', 'b'),
('engineering', 'phd', 'technology', 25, 50, 'What is nanotechnology?', 'Large scale manufacturing', 'Technology at molecular scale', 'Space technology', 'Agricultural technology', 'b'),
('science', 'phd', 'education', 25, 50, 'What is a thesis?', 'A short quiz', 'Extended research paper for degree', 'A textbook chapter', 'A lab report', 'b'),
('arts', 'phd', 'creative', 25, 50, 'What is ethnography?', 'Study of insects', 'Study of cultures through observation', 'Study of stars', 'Study of weather', 'b'),
('commerce', 'phd', 'business', 25, 50, 'What is econometrics?', 'Measuring buildings', 'Applying statistics to economic data', 'Counting inventory', 'Tracking shipments', 'b'),
('medical', 'phd', 'science', 25, 50, 'What is genomics?', 'Study of geography', 'Study of complete set of DNA', 'Study of geology', 'Study of grammar', 'b'),
('science', 'phd', 'science', 25, 50, 'What is a control group in an experiment?', 'The group that receives treatment', 'The group that does not receive treatment', 'The group that designs the experiment', 'The group that funds the research', 'b'),
('engineering', 'diploma', 'technology', 18, 30, 'What is AutoCAD used for?', 'Cooking', 'Computer-aided drafting and design', 'Accounting', 'Music production', 'b'),
('engineering', 'diploma', 'technology', 18, 30, 'What does AC stand for in electricity?', 'Active Current', 'Alternating Current', 'Automatic Circuit', 'Advanced Capacity', 'b'),
('computer-science', 'diploma', 'technology', 18, 30, 'What is a database?', 'A type of website', 'Organized collection of data', 'A programming language', 'An operating system', 'b'),
('computer-science', 'diploma', 'technology', 18, 30, 'What does LAN stand for?', 'Large Area Network', 'Local Area Network', 'Long Access Node', 'Linked Application Network', 'b'),
('medical', 'diploma', 'healthcare', 18, 30, 'What is first aid?', 'Surgery', 'Immediate care given before medical help', 'X-ray scanning', 'Blood testing', 'b'),
('medical', 'diploma', 'healthcare', 18, 30, 'What is a stethoscope used for?', 'Measuring temperature', 'Listening to heart and lung sounds', 'Checking blood pressure', 'Testing reflexes', 'b'),
('business', 'diploma', 'business', 18, 30, 'What is customer service?', 'Manufacturing products', 'Assisting customers with queries', 'Designing products', 'Delivering packages', 'b'),
('commerce', 'diploma', 'business', 18, 30, 'What is a balance sheet?', 'A gym equipment', 'Financial statement of assets and liabilities', 'A weighing scale', 'A scorecard', 'b'),
('computer-science', 'master', 'technology', 22, 40, 'What is cloud computing?', 'Weather forecasting', 'Delivering computing services over internet', 'Flying drones', 'Building satellites', 'b'),
('computer-science', 'master', 'technology', 22, 40, 'What is blockchain?', 'A building material', 'Decentralized digital ledger technology', 'A type of chain', 'A game', 'b'),
('business', 'master', 'business', 22, 40, 'What is corporate governance?', 'Government elections', 'System of rules for managing companies', 'Corporate parties', 'Team outings', 'b'),
('business', 'master', 'business', 22, 40, 'What is strategic management?', 'Daily office tasks', 'Long-term planning for organizational goals', 'Employee attendance', 'File management', 'b'),
('medical', 'master', 'healthcare', 22, 40, 'What is epidemiology?', 'Study of insects', 'Study of disease patterns in populations', 'Study of skin', 'Study of emotions', 'b'),
('medical', 'master', 'healthcare', 22, 40, 'What is telemedicine?', 'Medicine for telephones', 'Remote delivery of healthcare via technology', 'Television show about doctors', 'Telephone hotline', 'b'),
('engineering', 'master', 'technology', 22, 40, 'What is renewable energy?', 'Energy from coal', 'Energy from naturally replenishing sources', 'Nuclear energy', 'Energy from oil', 'b'),
('arts', 'master', 'media', 22, 40, 'What is investigative journalism?', 'Writing fiction', 'In-depth research on important issues', 'Sports commentary', 'Weather reporting', 'b'),
('science', '10th', 'science', 14, 20, 'Which gas do plants use for photosynthesis?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 'c'),
('science', '10th', 'science', 14, 20, 'What is the boiling point of water?', '50 C', '100 C', '150 C', '200 C', 'b'),
('commerce', '10th', 'business', 14, 20, 'What is a bank?', 'A playground', 'Institution that handles money', 'A hospital', 'A school', 'b'),
('commerce', '10th', 'business', 14, 20, 'What does ATM stand for?', 'Any Time Money', 'Automated Teller Machine', 'Automatic Transfer Machine', 'Advanced Teller Method', 'b'),
('arts', '10th', 'creative', 14, 20, 'What is a poem?', 'A mathematical formula', 'A literary work in verse', 'A science experiment', 'A cooking recipe', 'b'),
('arts', '10th', 'education', 14, 20, 'Who was the first Prime Minister of India?', 'Mahatma Gandhi', 'Jawaharlal Nehru', 'Sardar Patel', 'Dr. Ambedkar', 'b'),
('engineering', '10th', 'technology', 14, 20, 'What is electricity?', 'A type of water', 'Flow of electric charge', 'A chemical compound', 'A type of food', 'b'),
('engineering', '10th', 'technology', 14, 20, 'What is a circuit?', 'A type of race', 'Complete path for electric current', 'A type of game', 'A music device', 'b'),
('medical', '10th', 'healthcare', 14, 20, 'What is a doctor?', 'A person who builds houses', 'A person who treats patients', 'A person who teaches', 'A person who cooks', 'b'),
('medical', '10th', 'healthcare', 14, 20, 'Why should we wash hands?', 'To look clean', 'To prevent spread of germs', 'For fun', 'To waste water', 'b');



-- UPDATE MOLRE QUESTION


INSERT INTO career_questions (category, qualification, interest, age_min, age_max, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
('science', 'bachelor', 'science', 20, 35, 'What is the value of the speed of sound in dry air at 20°C?', '343 m/s', '300,000 km/s', '1500 m/s', '120 m/s', 'a'),
('science', '12th', 'science', 16, 25, 'Which gas is known as Laughing Gas?', 'Nitric Oxide', 'Nitrous Oxide', 'Nitrogen Dioxide', 'Ammonia', 'b'),
('science', 'bachelor', 'education', 20, 35, 'Who proposed the Theory of Relativity?', 'Isaac Newton', 'Albert Einstein', 'Stephen Hawking', 'Marie Curie', 'b'),
('science', '10th', 'science', 14, 20, 'What is the structural and functional unit of life?', 'Tissue', 'Organ', 'Cell', 'System', 'c'),
('science', 'bachelor', 'healthcare', 20, 35, 'What is the pH value of pure water?', '5', '7', '9', '11', 'b'),
('science', '12th', 'technology', 16, 25, 'What is the chemical symbol for Gold?', 'Ag', 'Au', 'Pb', 'Fe', 'b'),
('science', 'master', 'science', 22, 40, 'What type of lens is used to correct myopia?', 'Convex', 'Concave', 'Bifocal', 'Cylindrical', 'b'),
('science', '12th', 'science', 15, 25, 'Which subatomic particle has no charge?', 'Proton', 'Electron', 'Neutron', 'Positron', 'c'),
('science', 'bachelor', 'science', 20, 35, 'What is the chemical name of common salt?', 'Sodium Chloride', 'Sodium Carbonate', 'Potassium Chloride', 'Calcium Chloride', 'a'),
('science', '10th', 'science', 14, 20, 'What is the main source of energy for the Earth?', 'Earths Core', 'The Moon', 'The Sun', 'Nuclear Energy', 'c'),
('commerce', '12th', 'business', 16, 25, 'What is the accounting equation?', 'Assets = Liabilities + Equity', 'Income = Expense + Profit', 'Revenue = Sales - Cost', 'Assets = Revenue - Debt', 'a'),
('commerce', 'bachelor', 'business', 20, 35, 'What is a "Fixed Asset"?', 'Inventory', 'Cash', 'Machinery', 'Accounts Receivable', 'c'),
('commerce', '12th', 'business', 16, 25, 'What is "Depreciation"?', 'Increase in value', 'Reduction in value of an asset over time', 'Loan interest', 'Dividends', 'b'),
('commerce', 'bachelor', 'business', 20, 35, 'What is the primary goal of financial management?', 'Profit Maximization', 'Wealth Maximization', 'Tax Evasion', 'Cost Cutting', 'b'),
('commerce', 'master', 'business', 22, 40, 'What is a "Debenture"?', 'Type of stock', 'Long-term debt instrument', 'Short-term loan', 'Reserve fund', 'b'),
('commerce', '12th', 'business', 16, 25, 'What does SEBI stand for?', 'Stock Exchange Board of India', 'Securities and Exchange Board of India', 'Social Education Bureau of India', 'State Electronic Board of India', 'b'),
('commerce', 'bachelor', 'business', 20, 35, 'What is "Working Capital"?', 'Total Assets', 'Current Assets minus Current Liabilities', 'Share Capital', 'Fixed Assets', 'b'),
('commerce', '12th', 'business', 16, 25, 'What is an "Audit"?', 'Tax payment', 'Examination of financial records', 'Market research', 'Sales promotion', 'b'),
('commerce', '10th', 'business', 14, 20, 'What is the full form of GDP?', 'Gross Domestic Product', 'General Development Plan', 'Global Data Processing', 'Great Domestic Production', 'a'),
('commerce', 'bachelor', 'business', 20, 35, 'What is an "IPO"?', 'Internal Production Order', 'Initial Public Offering', 'Investment Portfolio Option', 'International Price Office', 'b'),
('commerce', '12th', 'business', 16, 25, 'What is "Double Entry System"?', 'Entering same data twice', 'Recording every transaction twice (debit/credit)', 'Two people making entries', 'Entry in two languages', 'b'),
('commerce', 'bachelor', 'business', 20, 35, 'What is a "Balance Sheet"?', 'List of daily sales', 'Statement showing assets and liabilities', 'Bank statement', 'Employee list', 'b'),
('commerce', 'master', 'business', 22, 40, 'What is "Cost of Capital"?', 'Price of raw materials', 'Minimum return expected by investors', 'Taxes paid', 'Office expenses', 'b'),
('commerce', '12th', 'business', 16, 25, 'What is "Petty Cash"?', 'Large bank deposit', 'Small amount of cash for minor expenses', 'Credit card limit', 'Foreign currency', 'b'),
('commerce', '10th', 'business', 14, 20, 'What is a "Cheque"?', 'A medical report', 'An order to a bank to pay a specific amount', 'A test paper', 'A shopping list', 'b'),
('arts', '12th', 'creative', 16, 25, 'What is the study of human population called?', 'Geography', 'Demography', 'History', 'Civics', 'b'),
('arts', 'bachelor', 'creative', 20, 35, 'Who wrote the play "Hamlet"?', 'Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Leo Tolstoy', 'b'),
('arts', '12th', 'media', 16, 25, 'What is the capital of Italy?', 'Paris', 'Madrid', 'Rome', 'Athens', 'c'),
('arts', 'bachelor', 'education', 20, 35, 'What is the study of human language called?', 'Philology', 'Linguistics', 'Theology', 'Mythology', 'b'),
('arts', '10th', 'creative', 14, 20, 'Which is the largest continent in the world?', 'Africa', 'Asia', 'Europe', 'North America', 'b'),
('arts', '12th', 'social-services', 16, 25, 'Who was the leader of the Civil Rights Movement in the US?', 'Abraham Lincoln', 'Martin Luther King Jr.', 'John F. Kennedy', 'George Washington', 'b'),
('arts', 'bachelor', 'media', 20, 35, 'What is the "Fourth Estate"?', 'Real Estate', 'The Judiciary', 'The Press/Media', 'Parliament', 'c'),
('arts', 'master', 'creative', 22, 40, 'What is "Archaeology"?', 'Study of stars', 'Study of past human life through artifacts', 'Study of insects', 'Study of oceans', 'b'),
('arts', '12th', 'education', 16, 25, 'Who founded the Maurya Empire?', 'Ashoka', 'Chandragupta Maurya', 'Bimbisara', 'Ajatashatru', 'b'),
('arts', '10th', 'creative', 14, 20, 'What is the national animal of India?', 'Lion', 'Tiger', 'Leopard', 'Elephant', 'b'),
('engineering', 'bachelor', 'technology', 20, 35, 'What is the primary function of a diode?', 'Amplify signal', 'Allow current in one direction', 'Store charge', 'Measure resistance', 'b'),
('engineering', 'diploma', 'technology', 18, 30, 'What does CNC stand for?', 'Computer Numerical Control', 'Central Network Connection', 'Creative Network Concept', 'Circular Node Command', 'a'),
('engineering', 'bachelor', 'technology', 20, 35, 'Which material is most commonly used in solar cells?', 'Iron', 'Silicon', 'Aluminium', 'Copper', 'b'),
('engineering', '12th', 'technology', 16, 25, 'What is the unit of Power?', 'Joule', 'Watt', 'Newton', 'Volt', 'b'),
('engineering', 'master', 'technology', 22, 40, 'What is "Thermodynamics"?', 'Study of sound', 'Study of heat and energy', 'Study of light', 'Study of motion', 'b'),
('engineering', 'bachelor', 'technology', 20, 35, 'What is a "Microcontroller"?', 'Large computer', 'Compact integrated circuit for specific tasks', 'Memory chip only', 'Monitor screen', 'b'),
('engineering', 'diploma', 'technology', 18, 30, 'What is the main component of steel?', 'Copper', 'Iron', 'Aluminium', 'Zinc', 'b'),
('engineering', '12th', 'technology', 16, 25, 'What is the boiling point of Ethanol?', '100 C', '78.37 C', '50 C', '120 C', 'b'),
('engineering', 'bachelor', 'technology', 20, 35, 'What is "CAD" in engineering?', 'Central Active Data', 'Computer Aided Design', 'Creative Auto Drawing', 'Complete Area Draft', 'b'),
('engineering', 'master', 'technology', 22, 40, 'What is "Aerodynamics"?', 'Study of water flow', 'Study of air flow around objects', 'Study of soil', 'Study of electricity', 'b'),
('medical', 'bachelor', 'healthcare', 20, 35, 'Which organ filters waste from the blood?', 'Lungs', 'Kidneys', 'Stomach', 'Pancreas', 'b'),
('medical', '12th', 'healthcare', 16, 25, 'What is the normal blood pressure for an adult?', '120/80 mmHg', '150/100 mmHg', '80/60 mmHg', '180/120 mmHg', 'a'),
('medical', 'bachelor', 'healthcare', 20, 35, 'What is the largest bone in the human body?', 'Skull', 'Femur', 'Ribs', 'Vertebrae', 'b'),
('medical', 'diploma', 'healthcare', 18, 30, 'Which vitamin is essential for blood clotting?', 'Vitamin A', 'Vitamin K', 'Vitamin C', 'Vitamin D', 'b'),
('medical', 'master', 'healthcare', 22, 40, 'What is "Oncology"?', 'Study of heart', 'Study of cancer', 'Study of skin', 'Study of eyes', 'b'),
('medical', '12th', 'healthcare', 16, 25, 'How many chambers does the human heart have?', '2', '3', '4', '5', 'c'),
('medical', 'bachelor', 'healthcare', 20, 35, 'What is "Haemoglobin"?', 'A type of bone', 'Protein in RBCs that carries oxygen', 'A muscle fiber', 'A nerve cell', 'b'),
('medical', 'diploma', 'healthcare', 18, 30, 'What is the primary function of antibiotics?', 'Kill viruses', 'Kill bacteria', 'Lower fever', 'Reduce pain', 'b'),
('medical', '12th', 'healthcare', 16, 25, 'What is "Vaccination"?', 'Treatment for injury', 'Method to provide immunity against diseases', 'Surgery', 'Diagnostic test', 'b'),
('medical', 'master', 'healthcare', 22, 40, 'What is "Pathology"?', 'Study of plants', 'Study of diseases', 'Study of rocks', 'Study of stars', 'b'),
('computer-science', 'bachelor', 'technology', 20, 35, 'What does "HTTPS" stand for?', 'Hyperlink Text Transfer System', 'Hypertext Transfer Protocol Secure', 'Home Tool Processing System', 'High Tech Power System', 'b'),
('computer-science', '12th', 'technology', 16, 25, 'Which language is known as the "Mother of all languages"?', 'Python', 'C', 'Java', 'Basic', 'b'),
('computer-science', 'bachelor', 'technology', 20, 35, 'What is "Cloud Computing"?', 'Storing data on local disk', 'Delivering computing services over the internet', 'Weather analysis', 'Satellite communication', 'b'),
('computer-science', 'diploma', 'technology', 18, 30, 'What is "Open Source Software"?', 'Paid software', 'Software with publicly available source code', 'Mobile apps only', 'Game software', 'b'),
('computer-science', 'master', 'technology', 22, 40, 'What is "Artificial Intelligence"?', 'Manual labor', 'Simulation of human intelligence by machines', 'Graphic design', 'Data entry', 'b'),
('computer-science', '12th', 'technology', 16, 25, 'What is an "IP Address"?', 'Postal address', 'Numerical label assigned to devices in a network', 'Memory slot', 'Processor model', 'b'),
('computer-science', 'bachelor', 'technology', 20, 35, 'What is "Full Stack Development"?', 'Only Frontend', 'Only Backend', 'Both Frontend and Backend development', 'Database only', 'c'),
('computer-science', 'diploma', 'technology', 18, 30, 'What is "RAM"?', 'Read Access Memory', 'Random Access Memory', 'Rapid Active Memory', 'Run Application Memory', 'b'),
('computer-science', '12th', 'technology', 16, 25, 'What does "WWW" stand for?', 'World Wide Web', 'Word Wide Web', 'World Web Wide', 'West Wide Web', 'a'),
('computer-science', 'master', 'technology', 22, 40, 'What is "Big Data"?', 'Large font size', 'Extremely large data sets analyzed for patterns', 'High speed internet', 'Video storage', 'b'),
('business', 'bachelor', 'business', 20, 35, 'What is "Market Research"?', 'Selling products', 'Gathering information about consumers needs', 'Hiring employees', 'Office cleaning', 'b'),
('business', '12th', 'business', 16, 25, 'What is a "Startup"?', 'Established corporation', 'New business typically aiming for rapid growth', 'Government agency', 'Non-profit group', 'b'),
('business', 'bachelor', 'business', 20, 35, 'What is "B2B"?', 'Business to Bank', 'Business to Business', 'Bank to Business', 'Buy to Build', 'b'),
('business', 'diploma', 'business', 18, 30, 'What is "Marketing Mix"?', 'Product Price Place Promotion', 'Sales Profit Cost Tax', 'Manager Employee Customer Owner', 'Plan Produce Sell Buy', 'a'),
('business', 'master', 'business', 22, 40, 'What is "Equity"?', 'Total Debt', 'Owner\'s stake in a company', 'Annual Revenue', 'Office furniture', 'b'),
('business', '12th', 'business', 16, 25, 'What is "Networking" in business?', 'Connecting computers', 'Building professional relationships', 'Writing emails', 'Attending parties', 'b'),
('business', 'bachelor', 'business', 20, 35, 'What is "CRM"?', 'Customer Relationship Management', 'Central Resource Management', 'Corporate Risk Method', 'Cost Reduction Model', 'a'),
('business', 'diploma', 'business', 18, 30, 'What is "Brand Loyalty"?', 'Buying various brands', 'Commitment of a customer to a specific brand', 'Advertising slogan', 'Logo design', 'b'),
('business', '12th', 'business', 16, 25, 'What is "E-commerce"?', 'Buying and selling on the internet', 'Electronic education', 'Email communication', 'Electronic currency', 'a'),
('business', 'master', 'business', 22, 40, 'What is "Venture Capital"?', 'Government funding', 'Financing provided to startups with high growth potential', 'Personal savings', 'Bank loan', 'b');

